version: '3'
services:
  order:
    build: order-service/.
    depends_on: 
      - rabbitmq
      - mongodb
    networks:
      - web
    restart: always
  product:
    build: product-service/.
    depends_on: 
      - rabbitmq
      - mongodb
    restart: always
    networks:
      - web
 
  auth:
    build: auth/.
    networks:
      - web
  nginx:
    image: nginx
    ports:
      - "8080:8080"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - web
  mongodb:
    image: mongo
    ports:
      - "27017:27017"
  rabbitmq: 
    image: rabbitmq:3-management
    environment:
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"
    ports:
      - "15672:15672"
      - "5672:5672"
    networks:
      - web
networks:
  web:
    driver: bridge