apiVersion: v1
kind: Service
metadata:
  name: auth
spec:
 type: NodePort
 ports:
  - port: 80
    targetPort: 8080
 selector:
    app: auth
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth
spec:
  replicas: 3
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
      - name: auth
        image: vaidehibhagwat/prototype_auth
        ports:
        - containerPort: 8080
        