apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hello-kubernetes-ingress
  annotations:
     kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: prototype.info
    http:
      paths:
      - pathType: Prefix
        path: /create
        backend:
          service:
            name: product
            port:
              number: 80
  - host: prototype.info
    http:
      paths:
      - pathType: Prefix
        path: /buy
        backend:
          service:
            name: product
            port:
              number: 80
  - host: prototype.info
    http:
      paths:
      - pathType: Prefix
        path: /health
        backend:
          service:
            name: product
            port:
              number: 80
  - host: prototype.info
    http:
      paths:
      - pathType: Prefix
        path: /authenticated
        backend:
          service:
            name: auth
            port:
              number: 80