apiVersion: v1
kind: Service
metadata:
  name: order
spec:
 type: NodePort
 ports:
  - port: 80
    targetPort: 8080
 selector:
    app: order
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: order
spec:
  replicas: 3
  selector:
    matchLabels:
      app: order
  template:
    metadata:
      labels:
        app: order
    spec:
      containers:
      - name: order
        image: vaidehibhagwat/prototype_order
        ports:
        - containerPort: 8080
        