apiVersion: v1
kind: Service
metadata:
  name: product
spec:
 type: NodePort
 ports:
  - port: 80
    targetPort: 8080
 selector:
    app: product
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: product
spec:
  replicas: 3
  selector:
    matchLabels:
      app: product
  template:
    metadata:
      labels:
        app: product
    spec:
      containers:
        - name: product
          image: vaidehibhagwat/prototype_product:1.0.0
          ports:
            - containerPort: 8080
        