apiVersion: v1
kind: Service
metadata:
  name: product
spec:
 type: NodePort
 ports:
  - port: 80
    targetPort: 8080
    nodePort: 32765
 selector:
    app: product
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: product
spec:
  replicas: 3
  selector:
    matchLabels:
      app: product
  template:
    metadata:
      labels:
        app: product
    spec:
      containers:
      - name: product
        image: vaidehibhagwat/prototype_product
        resources:
           limits:
             memory: 512Mi
             cpu: "1"
        ports:
        - containerPort: 8080
        